### ISSUE TITLE
Recommended Python version does not support recommended numpy version

### ISSUE THREAD

**Issue by jasonrorr** [tmytek/bbox-api#15]
## Description
When following the set-up instructions for the example code in Python, the packaged installer (bbox-api-master/pre-install/Python/python-3.7.7-webinstall.exe) installs Python 3.7.7. However, when trying to run the Setup.bat file to install the required packages, this fails because numpy 1.22.0 is not compatible with versions of Python below 3.8.

In order for the Setup.bat file to execute successfully, you must install Python 3.8 and run the Setup.bat so pip can install the required packages.

## Steps to Reproduce
1. On a fresh PC without Python installed, clone or download the bbox-api project
2. Install Python from the included webinstall.exe file (bbox-api-master/pre-install/Python/python-3.7.7-webinstall.exe)
3. Run Setup.bat
4. Setup will fail

## Expected Behavior
Setup should complete and install the required packages

## Current Behavior
Setup fails

### Device ID
N/A

### BBox FW Version
N/A

### BBox API Version
N/A

### BBox Suite Version
N/A

**Comment by jasonrorr** [comment]
This could be resolved by simply replacing the Python 3.7.7 installer with the stable release 3.8 installer from the Python.org website: [Python 3.8 for Windows x64 Stable Release](https://www.python.org/ftp/python/3.8.0/python-3.8.0-amd64-webinstall.exe) And updating the documentation/readme files.

**Comment by RaymondSuTMY** [comment]
Release at v1.6.7
