### ISSUE TITLE
setOperatingFreq always returns "Generic Error" (code 2) when invoking method from LabVIEW

### ISSUE THREAD

**Issue by jasonrorr** [tmytek/bbox-api#16]
## Description
When attempting to set the operating frequency of a BBox One using the TMYTEK BBox API DLL from LabVIEW, the function will always fail and return error code 2 ("Generic Error"). When attempting this same function call from Python it executes successfully and I am able to change the center frequency/operating frequency. I am also successful in changing the center/operating frequency of the BBox from the TMXLab software on the same computer.

![image](https://user-images.githubusercontent.com/42351495/231879086-e1b62c2c-1205-4278-9056-9a3ab143cf2a.png)

The generic error code is always returned, and the center/operating frequency is never changed when invoking this method in LabVIEW. Using the example program provided in this API repository returns the error, as well as running example code provided by NI (National Instruments) and invoking the method on my own in a very simple VI.

I believe this may have to do with numeric type casting/handling between LabVIEW and the TMYTEK API DLL, although I can't be sure since I do not have any insight into the source code behind the TMYTEK API DLL. When first loading the example code in LabVIEW, the BBoxOne.vi will throw a warning stating that the .NET Assembly being referenced has changed versions, from v3.3.8.0 to v3.3.18.0. Maybe something changed between those versions of the DLL that caused this example code to break, but again I can't be sure.

## Steps to Reproduce
1. Download or clone the bbox-api fresh from origin
2. Run the LabVIEW example provided (bbox-api-master/example/BBoxOne Series/LabVIEW/BBoxOne.vi)
3. All other methods will execute successfully except for setOperatingFreq (returns code 2)
4. If you use the method getOperatingFreq, it will always return the default operating freq for the device you're connected to. (In my case, the BBox One 5G 28GHz will always return 28 GHz)

## Expected Behavior
setOperatingFreq should succeed and change the operating frequency
## Current Behavior
Operating frequency does not change from default - as witnessed by running getOperatingFreq - and setOperatingFreq returns error code 2.
### Device ID
BBox One 5G 28 GHz (BNE-2840-G)
### BBox FW Version
1.2.14
### BBox API Version
3.3.18.0
### BBox Suite Version
Unsure

**Comment by RaymondSuTMY** [comment]
We have reproduced this issue.

Steps to Reproduce
1. Download or clone the bbox-api fresh from origin
2. Run the LabVIEW example provided (bbox-api-master/example/BBoxOne Series/LabVIEW/BBoxOne.vi)
3. All other methods will execute successfully except for setOperatingFreq (returns code 2)
4. If you use the method getOperatingFreq, it will always return the default operating freq for the device you're connected to. (In my case, the BBox One 5G 28GHz will always return 28 GHz)

---

The temporary solution
It works when step2 directly double click bbox-api\example\BBoxOne Series\LabVIEW \BBoxOneLabViewTest.lvproj to open project.

**Comment by RaymondSuTMY** [comment]
@jasonrorr 
The root cause is the .dll using relative path.
When user open the labview program outside the sample code folder, the working directory may changed.

**Comment by jasonrorr** [comment]
> @jasonrorr The root cause is the .dll using relative path. When user open the labview program outside the sample code folder, the working directory may changed.

When I am testing the example, I am not opening the VI outside of the sample code folder. Is the DLL using relative paths everywhere, or just for this one method call (setOperatingFreq)? I have also tested by opening the project first, then running the BBoxOneLabViewTest.vi from the project and I get the same error.

All the other API calls work without issue, if I write a VI with multiple API calls but don't include the setOperatingFreq method, I do not get any errors and I see the BBox update.

Also, if I want to use this method outside of the sample code folder, what relative path structure do I need to have in order for this method call to work?

**Comment by RaymondSuTMY** [comment]
> Also, if I want to use this method outside of the sample code folder, what relative path structure do I need to have in order for this method call to work?

The folder structure as below.

-- BBoxAPI.dll 
-- files/
| -- BeamTable/
| -- Configuration/
| -- Your device calibration table (such as D2230E013-28_28GHz.csv)
| -- Your device AAkit table (such as AAKIT_TMYTEK_28ONE_4x4_C2104L020-28.csv)
-- logs/

![1](https://user-images.githubusercontent.com/52556421/232655485-d7e78df9-f280-4467-a5c7-3415330d15bc.PNG)
![2](https://user-images.githubusercontent.com/52556421/232655509-77740222-22ec-4606-a957-acfb9b5c002f.PNG)
![3](https://user-images.githubusercontent.com/52556421/232655548-0e89918b-cebb-4908-86f7-671e2f712a60.PNG)

Can you upload the BBoxAPI log file in logs/ for analysis?

If the sample code can get calibration table and aakit table, GUI will show as below.

![4](https://user-images.githubusercontent.com/52556421/232656225-36516424-42db-449d-abfb-bea571296378.PNG)

**Comment by RaymondSuTMY** [comment]
@jasonrorr 

> When I am testing the example, I am not opening the VI outside of the sample code folder. Is the DLL using relative paths everywhere, or just for this one method call (setOperatingFreq)? I have also tested by opening the project first, then running the BBoxOneLabViewTest.vi from the project and I get the same error.

Can not open BBoxOneLabViewTest.vi at first.

It is necessary to open BBoxOneLabViewTest.lvproj by double click at the beginning.

**Comment by RaymondSuTMY** [comment]
I have added the GUI for setting and getting the current working directory path in the next release.
Before running the program, it is necessary to set the correct directory path.

---

Red part is for path settings and green part shows the table filenames in current_dir/files/ 

![10](https://user-images.githubusercontent.com/52556421/232699788-2151460c-19a5-4c4c-bec4-be33e55ee0ba.PNG)
![11](https://user-images.githubusercontent.com/52556421/232699803-8c961ba0-3c4e-4a1a-9268-44ae05d74f89.PNG)

**Comment by RaymondSuTMY** [comment]
Release at v1.6.7

**Comment by jasonrorr** [comment]
> > Also, if I want to use this method outside of the sample code folder, what relative path structure do I need to have in order for this method call to work?
> 
> The folder structure is as below.
> 
> -- BBoxAPI.dll -- files/ 
> | -- BeamTable/ 
> | -- Configuration/ 
> | -- Your device calibration table (such as D2230E013-28_28GHz.csv) 
> | -- Your device AAkit table (such as AAKIT_TMYTEK_28ONE_4x4_C2104L020-28.csv) 
> -- logs/

Hi Raymond,

After some testing, I was able to get the API to consistently find the relative `files` directory by calling kernel32.dll and setting the Windows working directory to directory containing the TMYTEK API dll and the rest of the folder structure. 

I'm guessing this is the addition you included in your update for v1.6.7, although I wasn't able to confirm because I am not able to open VIs saved in LabVIEW 2022 Q3.

Thanks for your help.
Jason
